# Generated by Django 3.1.2 on 2020-10-20 11:59

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField()),
                ('release_date', models.DateField()),
                ('starting_price', models.IntegerField()),
                ('cast', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('promo', embed_video.fields.EmbedVideoField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_full', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
            options={
                'verbose_name_plural': 'Shows',
            },
        ),
    ]
