# Generated by Django 3.1.2 on 2020-10-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('place', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('seats', models.JSONField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venues')),
            ],
            options={
                'verbose_name_plural': 'Seats',
            },
        ),
    ]
