# Generated by Django 3.1.2 on 2020-10-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_seats_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='color',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='price',
        ),
    ]
