# Generated by Django 3.1.2 on 2020-10-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_auto_20201022_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
