# Generated by Django 3.1.2 on 2020-10-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_seats_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='name',
            new_name='sname',
        ),
    ]
