# Generated by Django 3.1.2 on 2020-11-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_remove_seats_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='row',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seats',
            name='rp',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seats',
            name='rt',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
