# Generated by Django 3.1.2 on 2020-11-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20201102_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='venue',
        ),
    ]
