# Generated by Django 3.1.2 on 2020-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_bookings_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booked_seats',
            field=models.CharField(max_length=100),
        ),
    ]
