# Generated by Django 3.1.2 on 2020-11-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20201103_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
