# Generated by Django 3.1.2 on 2020-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20201104_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booked_seats_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
