# Generated by Django 3.1.2 on 2020-11-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookings_booked_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booked_seats_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
